export const cardInfo = [
  {
    date: 'April 16th 2020',
    title: 'The Mountains',
    author: 'John Appleseed',
    href: 'https://res.cloudinary.com/djuu2phoy/image/upload/v1628356313/assets/stories/mobile/mountainsDark_kwj25m.jpg',
  },
  {
    date: 'April 1th 2020',
    title: 'Sunset Cityscapes',
    author: 'Benjamin Cruz',
    href: 'https://res.cloudinary.com/djuu2phoy/image/upload/v1628356415/assets/stories/mobile/cityscapesDark_muxx6h.jpg',
  },
  {
    date: 'April 11th 2020',
    title: '18 Days Voyage',
    author: 'Alexei Borodin',
    href: 'https://res.cloudinary.com/djuu2phoy/image/upload/v1628356510/assets/stories/mobile/voyageDark_ndd55e.jpg',
  },
  {
    date: 'April 9th 2020',
    title: 'Architecturals',
    author: 'Samantha Brooke',
    href: 'https://res.cloudinary.com/djuu2phoy/image/upload/v1628356585/assets/stories/mobile/archDark_tbbmpf.jpg',
  },
  {
    date: 'April 7th 2020',
    title: 'World Tour 2019',
    author: 'Timothy Wagner',
    href: 'https://res.cloudinary.com/djuu2phoy/image/upload/v1628356313/assets/stories/mobile/mountainsDark_kwj25m.jpg',
  },
  {
    date: 'April 3rd 2020',
    title: 'Unforseen Corners',
    author: 'William Malcolm',
    href: 'https://res.cloudinary.com/djuu2phoy/image/upload/v1628356415/assets/stories/mobile/cityscapesDark_muxx6h.jpg',
  },
  {
    date: 'March 29th 2020',
    title: 'King on Africa: Part II',
    author: 'Tim Hillenburg',
    href: 'https://res.cloudinary.com/djuu2phoy/image/upload/v1628356510/assets/stories/mobile/voyageDark_ndd55e.jpg',
  },
  {
    date: 'March 21st 2020',
    title: 'The Trip to Nowhere',
    author: 'Felicia Rourke',
    href: 'https://res.cloudinary.com/djuu2phoy/image/upload/v1628356585/assets/stories/mobile/archDark_tbbmpf.jpg',
  },
  {
    date: 'March 19th 2020',
    title: 'Rage of the Sea',
    author: 'Mohammed Abdul',
    href: 'https://res.cloudinary.com/djuu2phoy/image/upload/v1628356313/assets/stories/mobile/mountainsDark_kwj25m.jpg',
  },
  {
    date: 'March 16th 2020',
    title: 'Running Free',
    author: 'Michelle',
    href: 'https://res.cloudinary.com/djuu2phoy/image/upload/v1628356415/assets/stories/mobile/cityscapesDark_muxx6h.jpg',
  },
  {
    date: 'March 11th 2020',
    title: 'Behind the Waves',
    author: 'Lamarr Wilson',
    href: 'https://res.cloudinary.com/djuu2phoy/image/upload/v1628356510/assets/stories/mobile/voyageDark_ndd55e.jpg',
  },
  {
    date: 'March 9th 2020',
    title: 'Calm Waters',
    author: 'Samantha Brooke',
    href: 'https://res.cloudinary.com/djuu2phoy/image/upload/v1628356585/assets/stories/mobile/archDark_tbbmpf.jpg',
  },
  {
    date: 'March 5th 2020',
    title: 'The Milky Way',
    author: 'Benjamin Cruz',
    href: 'https://res.cloudinary.com/djuu2phoy/image/upload/v1628356313/assets/stories/mobile/mountainsDark_kwj25m.jpg',
  },
  {
    date: 'March 4th 2020',
    title: 'Night at the Dark Forest',
    author: 'Mohammed Abdul',
    href: 'https://res.cloudinary.com/djuu2phoy/image/upload/v1628356415/assets/stories/mobile/cityscapesDark_muxx6h.jpg',
  },
  {
    date: 'March 1st 2020',
    title: "Somwarpet's Beauty",
    author: 'Michelle',
    href: 'https://res.cloudinary.com/djuu2phoy/image/upload/v1628356510/assets/stories/mobile/voyageDark_ndd55e.jpg',
  },
  {
    date: 'February 25th 2020',
    title: 'Land of Dreams',
    author: 'William Malcolm',
    href: 'https://res.cloudinary.com/djuu2phoy/image/upload/v1628356585/assets/stories/mobile/archDark_tbbmpf.jpg',
  },
];
